# Generated by Django 5.0.6 on 2024-07-04 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('product_key', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data1', models.FloatField(default=0, null=True)),
                ('data2', models.FloatField(default=0, null=True)),
                ('data3', models.FloatField(default=0, null=True)),
                ('data4', models.FloatField(default=0, null=True)),
                ('data5', models.FloatField(default=0, null=True)),
                ('data6', models.FloatField(default=0, null=True)),
                ('data7', models.FloatField(default=0, null=True)),
                ('data8', models.FloatField(default=0, null=True)),
                ('data9', models.FloatField(default=0, null=True)),
                ('data10', models.FloatField(default=0, null=True)),
                ('data11', models.FloatField(default=0, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
        ),
    ]
