# Generated by Django 5.0.6 on 2024-06-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_reading_data1_reading_data10_reading_data11_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='data1',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='data10',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='data11',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='data2',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='data3',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='data4',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='data5',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='data6',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='data7',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='data8',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='data9',
            field=models.FloatField(default=0, null=True),
        ),
    ]
